### ISSUE TITLE
Upstream to RustCrypto?

### ISSUE THREAD

**Issue by tarcieri** [quininer/kyber#1]
Hello from @RustCrypto again,

Would you be okay with giving the `kyber` crate to the @RustCrypto organization?

We would like to maintain an implementation of it eventually (it would probably not be based on yours, if you care)

**Comment by quininer** [comment]
I tried to add you to owner on crates.io earlier, maybe you missed it.

**Comment by quininer** [comment]
Oh, that's dilithium, I got confused.

**Comment by tarcieri** [comment]
Awesome, thank you! Invite accepted
